apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      myname: aniket
  template:
    metadata:
      name: pod5
      labels: 
        myname: aniket
    spec:
      containers:
      - name: co5
        image: nginx
        ports:
        - containerPort: 80


