apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 2
  selector:
    name: aniket
  template:
    metadata:
      name: mypod
      labels:
        name: aniket
    spec:
      containers:
      - name: co2
        image: nginx
