apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
spec:
  replicas: 2
  selector:
    matchExpressions:
    - {key: myname, operator: In, values: [aniket, aniiket, annniket]}
    - {key: env, operator: NotIn, values: [prod]}
  template:
    metadata:
      name: testpod
      labels:
        myname: aniket
    spec:
      containers:
      - name: co3
        image: httpd
